// lib/models/game_object_model.dart
class GameObjectModel {
  final String id;
  final String name;
  final String emoji;
  final String description;
  final List<String> keywords;
  final List<String> categories;
  final int basePoints;
  final int minLevel;
  final String imageHint;

  GameObjectModel({
    required this.id,
    required this.name,
    required this.emoji,
    required this.description,
    required this.keywords,
    required this.basePoints,
    required this.minLevel,
    this.categories = const [],
    this.imageHint = '',
  });

  static List<GameObjectModel> getAllObjects() {
    return [
      ..._getFruitsAndVegetables(),
      ..._getAnimals(),
      ..._getVehicles(),
      ..._getHouseholdItems(),
      ..._getSchoolSupplies(),
      ..._getToysAndGames(),
      ..._getFoodAndDrinks(),
      ..._getNatureAndWeather(),
      ..._getClothingAndAccessories(),
      ..._getTechnologyAndElectronics(),
    ];
  }

  // ==================== FRUITS ET LÉGUMES (15 objets) ====================
  static List<GameObjectModel> _getFruitsAndVegetables() {
    return [
      GameObjectModel(
        id: 'apple',
        name: 'Pomme',
        emoji: '🍎',
        description: 'Montre-moi une pomme !',
        keywords: ['pomme', 'apple', 'fruit', 'rouge', 'vert'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
        imageHint: 'pomme_rouge.jpg',
      ),
      GameObjectModel(
        id: 'banana',
        name: 'Banane',
        emoji: '🍌',
        description: 'Montre-moi une banane !',
        keywords: ['banane', 'banana', 'fruit', 'jaune'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'orange',
        name: 'Orange',
        emoji: '🍊',
        description: 'Montre-moi une orange !',
        keywords: ['orange', 'fruit', 'agrume'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'strawberry',
        name: 'Fraise',
        emoji: '🍓',
        description: 'Montre-moi une fraise !',
        keywords: ['fraise', 'strawberry', 'fruit', 'rouge'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'grapes',
        name: 'Raisin',
        emoji: '🍇',
        description: 'Montre-moi du raisin !',
        keywords: ['raisin', 'grapes', 'fruit', 'violet'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'watermelon',
        name: 'Pastèque',
        emoji: '🍉',
        description: 'Montre-moi une pastèque !',
        keywords: ['pastèque', 'watermelon', 'fruit', 'vert'],
        basePoints: 25,
        minLevel: 2,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'pear',
        name: 'Poire',
        emoji: '🍐',
        description: 'Montre-moi une poire !',
        keywords: ['poire', 'pear', 'fruit', 'vert'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'cherry',
        name: 'Cerise',
        emoji: '🍒',
        description: 'Montre-moi une cerise !',
        keywords: ['cerise', 'cherry', 'fruit', 'rouge'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'lemon',
        name: 'Citron',
        emoji: '🍋',
        description: 'Montre-moi un citron !',
        keywords: ['citron', 'lemon', 'fruit', 'jaune'],
        basePoints: 20,
        minLevel: 1,
        categories: ['fruit', 'nourriture'],
      ),
      GameObjectModel(
        id: 'carrot',
        name: 'Carotte',
        emoji: '🥕',
        description: 'Montre-moi une carotte !',
        keywords: ['carotte', 'carrot', 'légume', 'orange'],
        basePoints: 20,
        minLevel: 1,
        categories: ['legume', 'nourriture'],
      ),
      GameObjectModel(
        id: 'tomato',
        name: 'Tomate',
        emoji: '🍅',
        description: 'Montre-moi une tomate !',
        keywords: ['tomate', 'tomato', 'légume', 'fruit', 'rouge'],
        basePoints: 20,
        minLevel: 1,
        categories: ['legume', 'nourriture'],
      ),
      GameObjectModel(
        id: 'corn',
        name: 'Maïs',
        emoji: '🌽',
        description: 'Montre-moi un épi de maïs !',
        keywords: ['maïs', 'corn', 'légume', 'jaune'],
        basePoints: 20,
        minLevel: 1,
        categories: ['legume', 'nourriture'],
      ),
      GameObjectModel(
        id: 'broccoli',
        name: 'Brocoli',
        emoji: '🥦',
        description: 'Montre-moi un brocoli !',
        keywords: ['brocoli', 'broccoli', 'légume', 'vert'],
        basePoints: 25,
        minLevel: 2,
        categories: ['legume', 'nourriture'],
      ),
      GameObjectModel(
        id: 'cucumber',
        name: 'Concombre',
        emoji: '🥒',
        description: 'Montre-moi un concombre !',
        keywords: ['concombre', 'cucumber', 'légume', 'vert'],
        basePoints: 20,
        minLevel: 1,
        categories: ['legume', 'nourriture'],
      ),
      GameObjectModel(
        id: 'eggplant',
        name: 'Aubergine',
        emoji: '🍆',
        description: 'Montre-moi une aubergine !',
        keywords: ['aubergine', 'eggplant', 'légume', 'violet'],
        basePoints: 25,
        minLevel: 2,
        categories: ['legume', 'nourriture'],
      ),
    ];
  }

  // ==================== ANIMAUX (20 objets) ====================
  static List<GameObjectModel> _getAnimals() {
    return [
      GameObjectModel(
        id: 'cat',
        name: 'Chat',
        emoji: '🐱',
        description: 'Montre-moi un chat !',
        keywords: ['chat', 'cat', 'animal', 'félin', 'miaou'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'domestique'],
      ),
      GameObjectModel(
        id: 'dog',
        name: 'Chien',
        emoji: '🐶',
        description: 'Montre-moi un chien !',
        keywords: ['chien', 'dog', 'animal', 'canin', 'ouaf'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'domestique'],
      ),
      GameObjectModel(
        id: 'bird',
        name: 'Oiseau',
        emoji: '🐦',
        description: 'Montre-moi un oiseau !',
        keywords: ['oiseau', 'bird', 'animal', 'plume'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'fish',
        name: 'Poisson',
        emoji: '🐟',
        description: 'Montre-moi un poisson !',
        keywords: ['poisson', 'fish', 'animal', 'aquatique'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'aquatique'],
      ),
      GameObjectModel(
        id: 'rabbit',
        name: 'Lapin',
        emoji: '🐰',
        description: 'Montre-moi un lapin !',
        keywords: ['lapin', 'rabbit', 'animal', 'longues oreilles'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'domestique'],
      ),
      GameObjectModel(
        id: 'bear',
        name: 'Ours',
        emoji: '🐻',
        description: 'Montre-moi un ours !',
        keywords: ['ours', 'bear', 'animal', 'sauvage', 'grand'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'lion',
        name: 'Lion',
        emoji: '🦁',
        description: 'Montre-moi un lion !',
        keywords: ['lion', 'animal', 'sauvage', 'roi'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'elephant',
        name: 'Éléphant',
        emoji: '🐘',
        description: 'Montre-moi un éléphant !',
        keywords: ['éléphant', 'elephant', 'animal', 'grand', 'trompe'],
        basePoints: 35,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'giraffe',
        name: 'Girafe',
        emoji: '🦒',
        description: 'Montre-moi une girafe !',
        keywords: ['girafe', 'giraffe', 'animal', 'grand cou'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'monkey',
        name: 'Singe',
        emoji: '🐒',
        description: 'Montre-moi un singe !',
        keywords: ['singe', 'monkey', 'animal', 'sauvage'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'panda',
        name: 'Panda',
        emoji: '🐼',
        description: 'Montre-moi un panda !',
        keywords: ['panda', 'animal', 'noir', 'blanc'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'kangaroo',
        name: 'Kangourou',
        emoji: '🦘',
        description: 'Montre-moi un kangourou !',
        keywords: ['kangourou', 'kangaroo', 'animal', 'saut'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'zebra',
        name: 'Zèbre',
        emoji: '🦓',
        description: 'Montre-moi un zèbre !',
        keywords: ['zèbre', 'zebra', 'animal', 'rayures'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'fox',
        name: 'Renard',
        emoji: '🦊',
        description: 'Montre-moi un renard !',
        keywords: ['renard', 'fox', 'animal', 'roux'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'hedgehog',
        name: 'Hérisson',
        emoji: '🦔',
        description: 'Montre-moi un hérisson !',
        keywords: ['hérisson', 'hedgehog', 'animal', 'piquant'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'sauvage'],
      ),
      GameObjectModel(
        id: 'octopus',
        name: 'Poulpe',
        emoji: '🐙',
        description: 'Montre-moi un poulpe !',
        keywords: ['poulpe', 'octopus', 'animal', 'tentacules'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'aquatique'],
      ),
      GameObjectModel(
        id: 'dolphin',
        name: 'Dauphin',
        emoji: '🐬',
        description: 'Montre-moi un dauphin !',
        keywords: ['dauphin', 'dolphin', 'animal', 'aquatique'],
        basePoints: 30,
        minLevel: 3,
        categories: ['animal', 'aquatique'],
      ),
      GameObjectModel(
        id: 'turtle',
        name: 'Tortue',
        emoji: '🐢',
        description: 'Montre-moi une tortue !',
        keywords: ['tortue', 'turtle', 'animal', 'carapace'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'aquatique'],
      ),
      GameObjectModel(
        id: 'frog',
        name: 'Grenouille',
        emoji: '🐸',
        description: 'Montre-moi une grenouille !',
        keywords: ['grenouille', 'frog', 'animal', 'vert', 'saut'],
        basePoints: 25,
        minLevel: 2,
        categories: ['animal', 'aquatique'],
      ),
      GameObjectModel(
        id: 'unicorn',
        name: 'Licorne',
        emoji: '🦄',
        description: 'Montre-moi une licorne !',
        keywords: ['licorne', 'unicorn', 'magique', 'corne'],
        basePoints: 40,
        minLevel: 4,
        categories: ['magique', 'animal'],
      ),
    ];
  }

  // ==================== VEHICULES (15 objets) ====================
  static List<GameObjectModel> _getVehicles() {
    return [
      GameObjectModel(
        id: 'car',
        name: 'Voiture',
        emoji: '🚗',
        description: 'Montre-moi une voiture !',
        keywords: ['voiture', 'car', 'vehicle', 'auto', 'roues'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'truck',
        name: 'Camion',
        emoji: '🚚',
        description: 'Montre-moi un camion !',
        keywords: ['camion', 'truck', 'vehicle', 'poids lourd'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'bus',
        name: 'Bus',
        emoji: '🚌',
        description: 'Montre-moi un bus !',
        keywords: ['bus', 'autobus', 'vehicle', 'transport'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'motorcycle',
        name: 'Moto',
        emoji: '🏍️',
        description: 'Montre-moi une moto !',
        keywords: ['moto', 'motorcycle', 'vehicle', 'deux roues'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'bicycle',
        name: 'Vélo',
        emoji: '🚲',
        description: 'Montre-moi un vélo !',
        keywords: ['vélo', 'bicycle', 'bike', 'deux roues'],
        basePoints: 25,
        minLevel: 2,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'airplane',
        name: 'Avion',
        emoji: '✈️',
        description: 'Montre-moi un avion !',
        keywords: ['avion', 'airplane', 'vol', 'ciel'],
        basePoints: 35,
        minLevel: 3,
        categories: ['vehicule', 'transport', 'aerien'],
      ),
      GameObjectModel(
        id: 'helicopter',
        name: 'Hélicoptère',
        emoji: '🚁',
        description: 'Montre-moi un hélicoptère !',
        keywords: ['hélicoptère', 'helicopter', 'vol', 'rotor'],
        basePoints: 35,
        minLevel: 3,
        categories: ['vehicule', 'transport', 'aerien'],
      ),
      GameObjectModel(
        id: 'ship',
        name: 'Bateau',
        emoji: '🚢',
        description: 'Montre-moi un bateau !',
        keywords: ['bateau', 'ship', 'mer', 'navigation'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport', 'maritime'],
      ),
      GameObjectModel(
        id: 'boat',
        name: 'Bateau à voile',
        emoji: '⛵',
        description: 'Montre-moi un bateau à voile !',
        keywords: ['voilier', 'sailboat', 'mer', 'vent'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport', 'maritime'],
      ),
      GameObjectModel(
        id: 'train',
        name: 'Train',
        emoji: '🚆',
        description: 'Montre-moi un train !',
        keywords: ['train', 'chemin de fer', 'rails'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'subway',
        name: 'Métro',
        emoji: '🚇',
        description: 'Montre-moi un métro !',
        keywords: ['métro', 'subway', 'train', 'souterrain'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'tram',
        name: 'Tramway',
        emoji: '🚊',
        description: 'Montre-moi un tramway !',
        keywords: ['tramway', 'tram', 'transport'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'taxi',
        name: 'Taxi',
        emoji: '🚕',
        description: 'Montre-moi un taxi !',
        keywords: ['taxi', 'voiture', 'transport'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'transport'],
      ),
      GameObjectModel(
        id: 'ambulance',
        name: 'Ambulance',
        emoji: '🚑',
        description: 'Montre-moi une ambulance !',
        keywords: ['ambulance', 'urgence', 'medical'],
        basePoints: 30,
        minLevel: 3,
        categories: ['vehicule', 'urgence'],
      ),
      GameObjectModel(
        id: 'firetruck',
        name: 'Camion de pompiers',
        emoji: '🚒',
        description: 'Montre-moi un camion de pompiers !',
        keywords: ['pompier', 'firetruck', 'urgence', 'rouge'],
        basePoints: 35,
        minLevel: 3,
        categories: ['vehicule', 'urgence'],
      ),
    ];
  }

  // ==================== OBJETS DU QUOTIDIEN (15 objets) ====================
  static List<GameObjectModel> _getHouseholdItems() {
    return [
      GameObjectModel(
        id: 'book',
        name: 'Livre',
        emoji: '📚',
        description: 'Montre-moi un livre !',
        keywords: ['livre', 'book', 'lecture', 'pages'],
        basePoints: 30,
        minLevel: 3,
        categories: ['objet', 'ecole'],
      ),
      GameObjectModel(
        id: 'pen',
        name: 'Stylo',
        emoji: '✒️',
        description: 'Montre-moi un stylo !',
        keywords: ['stylo', 'pen', 'écrire', 'bille'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'ecole'],
      ),
      GameObjectModel(
        id: 'pencil',
        name: 'Crayon',
        emoji: '✏️',
        description: 'Montre-moi un crayon !',
        keywords: ['crayon', 'pencil', 'dessiner', 'écrire'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'ecole'],
      ),
      GameObjectModel(
        id: 'scissors',
        name: 'Ciseaux',
        emoji: '✂️',
        description: 'Montre-moi des ciseaux !',
        keywords: ['ciseaux', 'scissors', 'couper'],
        basePoints: 25,
        minLevel: 2,
        categories: ['objet', 'bureau'],
      ),
      GameObjectModel(
        id: 'cup',
        name: 'Tasse',
        emoji: '☕',
        description: 'Montre-moi une tasse !',
        keywords: ['tasse', 'cup', 'boire', 'café'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'cuisine'],
      ),
      GameObjectModel(
        id: 'plate',
        name: 'Assiette',
        emoji: '🍽️',
        description: 'Montre-moi une assiette !',
        keywords: ['assiette', 'plate', 'manger'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'cuisine'],
      ),
      GameObjectModel(
        id: 'fork',
        name: 'Fourchette',
        emoji: '🍴',
        description: 'Montre-moi une fourchette !',
        keywords: ['fourchette', 'fork', 'manger'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'cuisine'],
      ),
      GameObjectModel(
        id: 'spoon',
        name: 'Cuillère',
        emoji: '🥄',
        description: 'Montre-moi une cuillère !',
        keywords: ['cuillère', 'spoon', 'manger'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'cuisine'],
      ),
      GameObjectModel(
        id: 'key',
        name: 'Clé',
        emoji: '🔑',
        description: 'Montre-moi une clé !',
        keywords: ['clé', 'key', 'ouvrir', 'serrure'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'maison'],
      ),
      GameObjectModel(
        id: 'phone',
        name: 'Téléphone',
        emoji: '📱',
        description: 'Montre-moi un téléphone !',
        keywords: ['téléphone', 'phone', 'smartphone', 'appeler'],
        basePoints: 25,
        minLevel: 2,
        categories: ['objet', 'technologie'],
      ),
      GameObjectModel(
        id: 'watch',
        name: 'Montre',
        emoji: '⌚',
        description: 'Montre-moi une montre !',
        keywords: ['montre', 'watch', 'temps', 'heure'],
        basePoints: 25,
        minLevel: 2,
        categories: ['objet', 'accessoire'],
      ),
      GameObjectModel(
        id: 'glasses',
        name: 'Lunettes',
        emoji: '👓',
        description: 'Montre-moi des lunettes !',
        keywords: ['lunettes', 'glasses', 'voir', 'vision'],
        basePoints: 25,
        minLevel: 2,
        categories: ['objet', 'accessoire'],
      ),
      GameObjectModel(
        id: 'hat',
        name: 'Chapeau',
        emoji: '🧢',
        description: 'Montre-moi un chapeau !',
        keywords: ['chapeau', 'hat', 'tête', 'casquette'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'vêtement'],
      ),
      GameObjectModel(
        id: 'shoe',
        name: 'Chaussure',
        emoji: '👟',
        description: 'Montre-moi une chaussure !',
        keywords: ['chaussure', 'shoe', 'pied', 'basket'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'vêtement'],
      ),
      GameObjectModel(
        id: 'ball',
        name: 'Balle',
        emoji: '⚽',
        description: 'Montre-moi une balle !',
        keywords: ['balle', 'ball', 'jouer', 'sport'],
        basePoints: 20,
        minLevel: 1,
        categories: ['objet', 'sport'],
      ),
    ];
  }

  // ==================== ECOLE ET FOURNITURES (10 objets) ====================
  static List<GameObjectModel> _getSchoolSupplies() {
    return [
      GameObjectModel(
        id: 'backpack',
        name: 'Cartable',
        emoji: '🎒',
        description: 'Montre-moi un cartable !',
        keywords: ['cartable', 'backpack', 'école', 'sac'],
        basePoints: 25,
        minLevel: 2,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'notebook',
        name: 'Cahier',
        emoji: '📓',
        description: 'Montre-moi un cahier !',
        keywords: ['cahier', 'notebook', 'école', 'écrire'],
        basePoints: 20,
        minLevel: 1,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'ruler',
        name: 'Règle',
        emoji: '📏',
        description: 'Montre-moi une règle !',
        keywords: ['règle', 'ruler', 'mesurer', 'école'],
        basePoints: 20,
        minLevel: 1,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'eraser',
        name: 'Gomme',
        emoji: '🧽',
        description: 'Montre-moi une gomme !',
        keywords: ['gomme', 'eraser', 'effacer', 'école'],
        basePoints: 15,
        minLevel: 1,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'glue',
        name: 'Colle',
        emoji: '🩹',
        description: 'Montre-moi de la colle !',
        keywords: ['colle', 'glue', 'coller', 'école'],
        basePoints: 20,
        minLevel: 1,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'calculator',
        name: 'Calculatrice',
        emoji: '🧮',
        description: 'Montre-moi une calculatrice !',
        keywords: ['calculatrice', 'calculator', 'maths', 'école'],
        basePoints: 30,
        minLevel: 3,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'compass',
        name: 'Compas',
        emoji: '📐',
        description: 'Montre-moi un compas !',
        keywords: ['compas', 'compass', 'géométrie', 'école'],
        basePoints: 30,
        minLevel: 3,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'protractor',
        name: 'Rapporteur',
        emoji: '📐',
        description: 'Montre-moi un rapporteur !',
        keywords: ['rapporteur', 'protractor', 'angle', 'école'],
        basePoints: 30,
        minLevel: 3,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'marker',
        name: 'Marqueur',
        emoji: '🖍️',
        description: 'Montre-moi un marqueur !',
        keywords: ['marqueur', 'marker', 'colorier', 'école'],
        basePoints: 20,
        minLevel: 1,
        categories: ['ecole', 'objet'],
      ),
      GameObjectModel(
        id: 'tape',
        name: 'Ruban adhésif',
        emoji: '📦',
        description: 'Montre-moi du ruban adhésif !',
        keywords: ['ruban', 'tape', 'coller', 'école'],
        basePoints: 20,
        minLevel: 1,
        categories: ['ecole', 'objet'],
      ),
    ];
  }

  // ==================== JOUETS ET JEUX (10 objets) ====================
  static List<GameObjectModel> _getToysAndGames() {
    return [
      GameObjectModel(
        id: 'teddy_bear',
        name: 'Ours en peluche',
        emoji: '🧸',
        description: 'Montre-moi un ours en peluche !',
        keywords: ['peluche', 'teddy', 'ours', 'doudou'],
        basePoints: 25,
        minLevel: 2,
        categories: ['jouet', 'enfant'],
      ),
      GameObjectModel(
        id: 'lego',
        name: 'Lego',
        emoji: '🧱',
        description: 'Montre-moi une brique Lego !',
        keywords: ['lego', 'brique', 'construction', 'jouet'],
        basePoints: 25,
        minLevel: 2,
        categories: ['jouet', 'jeu'],
      ),
      GameObjectModel(
        id: 'doll',
        name: 'Poupée',
        emoji: '🎎',
        description: 'Montre-moi une poupée !',
        keywords: ['poupée', 'doll', 'jouet', 'enfant'],
        basePoints: 25,
        minLevel: 2,
        categories: ['jouet', 'enfant'],
      ),
      GameObjectModel(
        id: 'puzzle',
        name: 'Puzzle',
        emoji: '🧩',
        description: 'Montre-moi un puzzle !',
        keywords: ['puzzle', 'casse-tête', 'jeu', 'pièces'],
        basePoints: 25,
        minLevel: 2,
        categories: ['jouet', 'jeu'],
      ),
      GameObjectModel(
        id: 'yo_yo',
        name: 'Yo-yo',
        emoji: '🪀',
        description: 'Montre-moi un yo-yo !',
        keywords: ['yoyo', 'jouet', 'ficelle'],
        basePoints: 20,
        minLevel: 1,
        categories: ['jouet', 'jeu'],
      ),
      GameObjectModel(
        id: 'kite',
        name: 'Cerf-volant',
        emoji: '🪁',
        description: 'Montre-moi un cerf-volant !',
        keywords: ['cerf-volant', 'kite', 'vent', 'voler'],
        basePoints: 25,
        minLevel: 2,
        categories: ['jouet', 'extérieur'],
      ),
      GameObjectModel(
        id: 'marbles',
        name: 'Billes',
        emoji: '🔮',
        description: 'Montre-moi des billes !',
        keywords: ['billes', 'marbles', 'jouer', 'verre'],
        basePoints: 20,
        minLevel: 1,
        categories: ['jouet', 'jeu'],
      ),
      GameObjectModel(
        id: 'train_toy',
        name: 'Train jouet',
        emoji: '🚂',
        description: 'Montre-moi un train jouet !',
        keywords: ['train', 'jouet', 'rails', 'locomotive'],
        basePoints: 30,
        minLevel: 3,
        categories: ['jouet', 'jeu'],
      ),
      GameObjectModel(
        id: 'rc_car',
        name: 'Voiture télécommandée',
        emoji: '🚗',
        description: 'Montre-moi une voiture télécommandée !',
        keywords: ['télécommandée', 'rc', 'voiture', 'jouet'],
        basePoints: 35,
        minLevel: 3,
        categories: ['jouet', 'technologie'],
      ),
      GameObjectModel(
        id: 'board_game',
        name: 'Jeu de société',
        emoji: '🎲',
        description: 'Montre-moi un jeu de société !',
        keywords: ['société', 'board', 'jeu', 'plateau'],
        basePoints: 30,
        minLevel: 3,
        categories: ['jouet', 'jeu'],
      ),
    ];
  }

  // ==================== NOURRITURE ET BOISSONS (10 objets) ====================
  static List<GameObjectModel> _getFoodAndDrinks() {
    return [
      GameObjectModel(
        id: 'pizza',
        name: 'Pizza',
        emoji: '🍕',
        description: 'Montre-moi une pizza !',
        keywords: ['pizza', 'fromage', 'tomate', 'italien'],
        basePoints: 30,
        minLevel: 3,
        categories: ['nourriture', 'plat'],
      ),
      GameObjectModel(
        id: 'burger',
        name: 'Hamburger',
        emoji: '🍔',
        description: 'Montre-moi un hamburger !',
        keywords: ['burger', 'hamburger', 'fast-food', 'sandwich'],
        basePoints: 25,
        minLevel: 2,
        categories: ['nourriture', 'fast-food'],
      ),
      GameObjectModel(
        id: 'fries',
        name: 'Frites',
        emoji: '🍟',
        description: 'Montre-moi des frites !',
        keywords: ['frites', 'fries', 'patates', 'pommes de terre'],
        basePoints: 20,
        minLevel: 1,
        categories: ['nourriture', 'fast-food'],
      ),
      GameObjectModel(
        id: 'ice_cream',
        name: 'Glace',
        emoji: '🍦',
        description: 'Montre-moi une glace !',
        keywords: ['glace', 'ice cream', 'dessert', 'froid'],
        basePoints: 25,
        minLevel: 2,
        categories: ['nourriture', 'dessert'],
      ),
      GameObjectModel(
        id: 'cake',
        name: 'Gâteau',
        emoji: '🍰',
        description: 'Montre-moi un gâteau !',
        keywords: ['gâteau', 'cake', 'dessert', 'anniversaire'],
        basePoints: 30,
        minLevel: 3,
        categories: ['nourriture', 'dessert'],
      ),
      GameObjectModel(
        id: 'bread',
        name: 'Pain',
        emoji: '🍞',
        description: 'Montre-moi du pain !',
        keywords: ['pain', 'bread', 'baguette', 'céréales'],
        basePoints: 20,
        minLevel: 1,
        categories: ['nourriture', 'boulangerie'],
      ),
      GameObjectModel(
        id: 'cheese',
        name: 'Fromage',
        emoji: '🧀',
        description: 'Montre-moi du fromage !',
        keywords: ['fromage', 'cheese', 'lait', 'crémeux'],
        basePoints: 20,
        minLevel: 1,
        categories: ['nourriture', 'produit laitier'],
      ),
      GameObjectModel(
        id: 'milk',
        name: 'Lait',
        emoji: '🥛',
        description: 'Montre-moi du lait !',
        keywords: ['lait', 'milk', 'boire', 'calcium'],
        basePoints: 20,
        minLevel: 1,
        categories: ['boisson', 'produit laitier'],
      ),
      GameObjectModel(
        id: 'juice',
        name: 'Jus de fruit',
        emoji: '🧃',
        description: 'Montre-moi un jus de fruit !',
        keywords: ['jus', 'juice', 'fruit', 'boire'],
        basePoints: 20,
        minLevel: 1,
        categories: ['boisson', 'fruit'],
      ),
      GameObjectModel(
        id: 'soda',
        name: 'Soda',
        emoji: '🥤',
        description: 'Montre-moi un soda !',
        keywords: ['soda', 'coca', 'boisson', 'gazeux'],
        basePoints: 20,
        minLevel: 1,
        categories: ['boisson', 'gazeux'],
      ),
    ];
  }

  // ==================== NATURE ET MÉTÉO (5 objets) ====================
  static List<GameObjectModel> _getNatureAndWeather() {
    return [
      GameObjectModel(
        id: 'tree',
        name: 'Arbre',
        emoji: '🌳',
        description: 'Montre-moi un arbre !',
        keywords: ['arbre', 'tree', 'nature', 'vert', 'feuilles'],
        basePoints: 20,
        minLevel: 1,
        categories: ['nature', 'plante'],
      ),
      GameObjectModel(
        id: 'flower',
        name: 'Fleur',
        emoji: '🌸',
        description: 'Montre-moi une fleur !',
        keywords: ['fleur', 'flower', 'nature', 'pétales'],
        basePoints: 20,
        minLevel: 1,
        categories: ['nature', 'plante'],
      ),
      GameObjectModel(
        id: 'sun',
        name: 'Soleil',
        emoji: '☀️',
        description: 'Montre-moi le soleil !',
        keywords: ['soleil', 'sun', 'lumière', 'chaud'],
        basePoints: 25,
        minLevel: 2,
        categories: ['météo', 'astronomie'],
      ),
      GameObjectModel(
        id: 'moon',
        name: 'Lune',
        emoji: '🌙',
        description: 'Montre-moi la lune !',
        keywords: ['lune', 'moon', 'nuit', 'étoiles'],
        basePoints: 25,
        minLevel: 2,
        categories: ['astronomie', 'nuit'],
      ),
      GameObjectModel(
        id: 'star',
        name: 'Étoile',
        emoji: '⭐',
        description: 'Montre-moi une étoile !',
        keywords: ['étoile', 'star', 'ciel', 'nuit', 'brille'],
        basePoints: 30,
        minLevel: 3,
        categories: ['astronomie', 'nuit'],
      ),
    ];
  }

  // ==================== VÊTEMENTS ET ACCESSOIRES (10 objets) ====================
  static List<GameObjectModel> _getClothingAndAccessories() {
    return [
      GameObjectModel(
        id: 't_shirt',
        name: 'T-shirt',
        emoji: '👕',
        description: 'Montre-moi un t-shirt !',
        keywords: ['t-shirt', 'tee-shirt', 'vêtement', 'haut'],
        basePoints: 20,
        minLevel: 1,
        categories: ['vêtement', 'haut'],
      ),
      GameObjectModel(
        id: 'pants',
        name: 'Pantalon',
        emoji: '👖',
        description: 'Montre-moi un pantalon !',
        keywords: ['pantalon', 'pants', 'vêtement', 'bas'],
        basePoints: 20,
        minLevel: 1,
        categories: ['vêtement', 'bas'],
      ),
      GameObjectModel(
        id: 'dress',
        name: 'Robe',
        emoji: '👗',
        description: 'Montre-moi une robe !',
        keywords: ['robe', 'dress', 'vêtement', 'fille'],
        basePoints: 25,
        minLevel: 2,
        categories: ['vêtement', 'femme'],
      ),
      GameObjectModel(
        id: 'jacket',
        name: 'Veste',
        emoji: '🧥',
        description: 'Montre-moi une veste !',
        keywords: ['veste', 'jacket', 'vêtement', 'chaud'],
        basePoints: 25,
        minLevel: 2,
        categories: ['vêtement', 'haut'],
      ),
      GameObjectModel(
        id: 'scarf',
        name: 'Écharpe',
        emoji: '🧣',
        description: 'Montre-moi une écharpe !',
        keywords: ['écharpe', 'scarf', 'hiver', 'cou'],
        basePoints: 20,
        minLevel: 1,
        categories: ['accessoire', 'hiver'],
      ),
      GameObjectModel(
        id: 'gloves',
        name: 'Gants',
        emoji: '🧤',
        description: 'Montre-moi des gants !',
        keywords: ['gants', 'gloves', 'mains', 'hiver'],
        basePoints: 20,
        minLevel: 1,
        categories: ['accessoire', 'hiver'],
      ),
      GameObjectModel(
        id: 'socks',
        name: 'Chaussettes',
        emoji: '🧦',
        description: 'Montre-moi des chaussettes !',
        keywords: ['chaussettes', 'socks', 'pieds', 'vêtement'],
        basePoints: 15,
        minLevel: 1,
        categories: ['vêtement', 'bas'],
      ),
      GameObjectModel(
        id: 'belt',
        name: 'Ceinture',
        emoji: '⛓️',
        description: 'Montre-moi une ceinture !',
        keywords: ['ceinture', 'belt', 'pantalon', 'accessoire'],
        basePoints: 20,
        minLevel: 1,
        categories: ['accessoire', 'vêtement'],
      ),
      GameObjectModel(
        id: 'necklace',
        name: 'Collier',
        emoji: '📿',
        description: 'Montre-moi un collier !',
        keywords: ['collier', 'necklace', 'bijou', 'cou'],
        basePoints: 25,
        minLevel: 2,
        categories: ['bijou', 'accessoire'],
      ),
      GameObjectModel(
        id: 'ring',
        name: 'Bague',
        emoji: '💍',
        description: 'Montre-moi une bague !',
        keywords: ['bague', 'ring', 'bijou', 'doigt'],
        basePoints: 25,
        minLevel: 2,
        categories: ['bijou', 'accessoire'],
      ),
    ];
  }

  // ==================== TECHNOLOGIE ET ÉLECTRONIQUE (10 objets) ====================
  static List<GameObjectModel> _getTechnologyAndElectronics() {
    return [
      GameObjectModel(
        id: 'computer',
        name: 'Ordinateur',
        emoji: '💻',
        description: 'Montre-moi un ordinateur !',
        keywords: ['ordinateur', 'computer', 'pc', 'écran'],
        basePoints: 35,
        minLevel: 3,
        categories: ['technologie', 'électronique'],
      ),
      GameObjectModel(
        id: 'tablet',
        name: 'Tablette',
        emoji: '📱',
        description: 'Montre-moi une tablette !',
        keywords: ['tablette', 'tablet', 'ipad', 'écran'],
        basePoints: 30,
        minLevel: 3,
        categories: ['technologie', 'électronique'],
      ),
      GameObjectModel(
        id: 'tv',
        name: 'Télévision',
        emoji: '📺',
        description: 'Montre-moi une télévision !',
        keywords: ['télévision', 'tv', 'écran', 'regarder'],
        basePoints: 35,
        minLevel: 3,
        categories: ['technologie', 'électronique'],
      ),
      GameObjectModel(
        id: 'headphones',
        name: 'Casque audio',
        emoji: '🎧',
        description: 'Montre-moi un casque audio !',
        keywords: ['casque', 'headphones', 'audio', 'écouter'],
        basePoints: 25,
        minLevel: 2,
        categories: ['technologie', 'audio'],
      ),
      GameObjectModel(
        id: 'speaker',
        name: 'Enceinte',
        emoji: '🔊',
        description: 'Montre-moi une enceinte !',
        keywords: ['enceinte', 'speaker', 'son', 'musique'],
        basePoints: 25,
        minLevel: 2,
        categories: ['technologie', 'audio'],
      ),
      GameObjectModel(
        id: 'camera',
        name: 'Appareil photo',
        emoji: '📷',
        description: 'Montre-moi un appareil photo !',
        keywords: ['appareil photo', 'camera', 'photo', 'prendre'],
        basePoints: 30,
        minLevel: 3,
        categories: ['technologie', 'photo'],
      ),
      GameObjectModel(
        id: 'printer',
        name: 'Imprimante',
        emoji: '🖨️',
        description: 'Montre-moi une imprimante !',
        keywords: ['imprimante', 'printer', 'papier', 'impression'],
        basePoints: 30,
        minLevel: 3,
        categories: ['technologie', 'bureau'],
      ),
      GameObjectModel(
        id: 'mouse',
        name: 'Souris',
        emoji: '🖱️',
        description: 'Montre-moi une souris d\'ordinateur !',
        keywords: ['souris', 'mouse', 'ordinateur', 'cliquer'],
        basePoints: 25,
        minLevel: 2,
        categories: ['technologie', 'bureau'],
      ),
      GameObjectModel(
        id: 'keyboard',
        name: 'Clavier',
        emoji: '⌨️',
        description: 'Montre-moi un clavier !',
        keywords: ['clavier', 'keyboard', 'ordinateur', 'taper'],
        basePoints: 25,
        minLevel: 2,
        categories: ['technologie', 'bureau'],
      ),
      GameObjectModel(
        id: 'usb',
        name: 'Clé USB',
        emoji: '💾',
        description: 'Montre-moi une clé USB !',
        keywords: ['usb', 'clé', 'stockage', 'données'],
        basePoints: 20,
        minLevel: 1,
        categories: ['technologie', 'stockage'],
      ),
    ];
  }

  // Méthodes utilitaires
  static List<GameObjectModel> getObjectsByLevel(int level) {
    return getAllObjects().where((obj) => obj.minLevel <= level).toList();
  }

  static List<GameObjectModel> getObjectsByCategory(String category) {
    return getAllObjects().where((obj) => obj.categories.contains(category)).toList();
  }

  static List<String> getAllCategories() {
    final categories = <String>{};
    for (var obj in getAllObjects()) {
      categories.addAll(obj.categories);
    }
    return categories.toList();
  }

  static int getTotalObjectsCount() {
    return getAllObjects().length;
  }
}